import { useState } from 'react';
import { Sparkles, ChevronDown, ChevronUp, RefreshCw } from 'lucide-react';
import { Tooltip, TooltipTrigger, TooltipContent } from './ui/tooltip';

/* AI summary at the top of a knowledge article, technician view only.
 *
 * A requester wants the article; a technician also has to judge whether it can be TRUSTED — is it
 * approved, is anyone scheduled to re-verify it, what do readers say, what does it affect. Those
 * answers are otherwise scattered across the tab strip, the right rail and the schedule popup, so
 * this block states them once and makes each one a link to where it lives. */

export function KnowledgeAiSummary({
  summary,
  context,
  points = [],
  generatedBy = 'ServiceOps AI',
}: {
  /** What the article says, in one or two paragraphs — enough to act on without opening it. */
  summary: string[];
  /** How the article is doing — status, folder, readership, feedback. */
  context?: string;
  points?: string[];
  generatedBy?: string;
}) {
  const [open, setOpen] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  return (
    <div
      className="rounded-xl border border-[#E7E1F7]"
      style={{ background: 'linear-gradient(118deg, #FCFBFF 0%, #F6F3FE 55%, #FCF3FA 100%)' }}
    >
      <div className="flex items-center gap-2 px-4 py-3">
        <Sparkles size={16} className="flex-shrink-0 text-[#8B5CF6]" />
        <span className="text-[13px] font-semibold text-[#364658]">
          {refreshing ? 'Generating summary…' : 'AI Summary'}
        </span>
        <div className="ml-auto flex items-center gap-1">
          <Tooltip>
            <TooltipTrigger asChild>
              <button
                onClick={() => {
                  setRefreshing(true);
                  setTimeout(() => setRefreshing(false), 1600);
                }}
                disabled={refreshing}
                className="flex size-7 items-center justify-center rounded transition-colors hover:bg-white/70"
              >
                <RefreshCw size={13} className={`text-[#7B8FA5] ${refreshing ? 'animate-spin' : ''}`} />
              </button>
            </TooltipTrigger>
            <TooltipContent>Regenerate</TooltipContent>
          </Tooltip>
          <button
            onClick={() => setOpen(!open)}
            className="flex size-7 items-center justify-center rounded transition-colors hover:bg-white/70"
          >
            {open ? <ChevronUp size={15} className="text-[#7B8FA5]" /> : <ChevronDown size={15} className="text-[#7B8FA5]" />}
          </button>
        </div>
      </div>

      {open && (
        <div className="px-4 pb-4">
          <div className="space-y-2.5">
            {summary.map((para, i) => (
              <p key={i} className="text-[13px] leading-relaxed text-[#364658]">{para}</p>
            ))}
            {context && <p className="text-[13px] leading-relaxed text-[#7B8FA5]">{context}</p>}
          </div>

          {points.length > 0 && (
            <>
              <div className="mt-3 text-[11px] font-semibold uppercase tracking-[0.04em] text-[#7B8FA5]">Key points</div>
              <ul className="mt-1.5 space-y-1.5">
                {points.map((p, i) => (
                  <li key={i} className="flex items-start gap-2 text-[13px] leading-relaxed text-[#364658]">
                    <span className="mt-[7px] size-1 flex-shrink-0 rounded-full bg-[#8B5CF6]" />
                    <span className="min-w-0">{p}</span>
                  </li>
                ))}
              </ul>
            </>
          )}

          <div className="mt-3 text-[11px] text-[#A7B0BD]">Generated by {generatedBy}</div>
        </div>
      )}
    </div>
  );
}
